# config.py

APP_NAME = {
    "pt": "Localizador de Termos em PDFs",
    "en": "PDF Term Finder"
}

# Dicionário de mensagens para diferentes idiomas
MESSAGES = {
    "pt": {
        "upload_instructions": "Faça o upload de um arquivo PDF e insira os termos (palavras, frases, tópicos) que você deseja encontrar. Cada termo deve estar em uma nova linha na caixa de texto abaixo.",
        "search_terms_input_label": "Insira seus termos de busca (um por linha):",
        "search_terms_input_placeholder": "Exemplo:\nGovernança Corporativa\nLei Geral de Proteção de Dados\nRelatório Financeiro\nSustentabilidade",
        "file_uploader_label": "Escolha um ou mais arquivos PDF",
        "processing_spinner": "Processando PDF...",
        "results_header": "Resultados:",
        "terms_found_header": "Termos de busca encontrados no documento:",
        "relevant_snippets_header": "Trechos Relevantes:",
        "no_snippets_found": "Nenhum trecho encontrado para os termos especificados.",
        "no_terms_found": "Nenhum dos termos de busca foi encontrado no documento.",
        "please_enter_terms": "Por favor, insira os termos de busca na caixa de texto.",
        "please_upload_file": "Por favor, faça o upload de um ou mais arquivos PDF.",
        "error_reading_pdf": "Erro ao ler o PDF:",
        "pdf_corruption_warning": "Por favor, verifique se o arquivo PDF não está corrompido, protegido por senha ou em um formato inválido.",
        "select_language": "Selecione o Idioma:",
        "no_keywords_info": "Nenhuma palavra-chave encontrada (exceto stopwords e palavras curtas).",
        "search_options_header": "Opções de Busca:",
        "case_sensitive_checkbox": "Diferenciar maiúsculas/minúsculas",
        "whole_word_checkbox": "Apenas palavras inteiras",
        "stats_header": "Estatísticas do Documento:",
        "total_words_count": "Total de palavras no documento:",
        "term_occurrences": "Ocorrências dos Termos:",
        "download_results_button": "Baixar Resultados (.txt)",
        "download_filename": "resultados_busca.txt",
        "page_number_label": "Página:",
        "clear_button_label": "Limpar Tudo",
        "pdf_manual_conversion_guidance": "Se este erro persistir, o PDF pode ter uma proteção avançada. Tente converter o PDF para texto simples (TXT) usando uma ferramenta online (ex: 'PDF para TXT' do Smallpdf ou Adobe Acrobat online) e depois carregue o TXT no campo de texto para busca, ou use um PDF que não tenha essa proteção.",
        "process_button_label": "Processar Busca",
        "initial_guidance": "Faça o upload de um ou mais arquivos PDF e insira os termos de busca. Em seguida, clique em 'Processar Busca'.",
        "copy_results_button": "Copiar Resultados",
        "copy_instructions": "Copie o texto abaixo:",
        "results_from_file": "Resultados do arquivo:",
        "processing_file": "Processando arquivo:",
        "filter_snippets_label": "Filtrar trechos por termo:",
        "sort_snippets_label": "Ordenar trechos por:",
        "sort_option_page": "Página (crescente)",
        "sort_option_file_page": "Arquivo e Página (crescente)",
        "all_terms_filter": "Todos os Termos",
        "enable_regex_checkbox": "Habilitar Busca Regex",
        "about_header": "Sobre / Ajuda",
        "about_content_1": "Este aplicativo permite que você extraia texto de PDFs e busque por termos ou frases específicas. Você pode carregar múltiplos PDFs e personalizar sua busca.",
        "about_content_2": "Os resultados incluem estatísticas do documento e trechos relevantes com o número da página e o arquivo de origem. Você pode baixar ou copiar os resultados.",
        "about_limitations": "**Limitações Conhecidas:**\n- **PDFs Protegidos/Criptografados:** Alguns PDFs com proteção avançada não podem ser lidos diretamente. Uma sugestão aparece se houver um erro de leitura.\n- **Performance:** PDFs muito grandes podem demorar para processar e consumir mais memória.",
        "process_button_icon": "🚀", # ÍCONE CORRIGIDO
        "clear_button_icon": "🗑️", # ÍCONE CORRIGIDO
        "download_button_icon": "📥", # ÍCONE CORRIGIDO
        "copy_button_icon": "📋", # ÍCONE CORRIGIDO
        "regex_help_text": "Use sintaxe de Expressão Regular. Ex: 'email:(\\S+@\\S+)' para emails.",
        "expander_results_header": "Ver Resultados",
        "expander_results_header_with_count": "Ver Resultados ({count} trechos encontrados)",
        "favicon_icon": "📚"
    },
    "en": {
        "upload_instructions": "Upload one or more PDF files and enter the terms (words, phrases, topics) you want to find. Each term should be on a new line in the text box below.",
        "search_terms_input_label": "Enter your search terms (one per line):",
        "search_terms_input_placeholder": "Example:\nCorporate Governance\nGeneral Data Protection Law\nFinancial Report\nSustainability",
        "file_uploader_label": "Choose one or more PDF files",
        "processing_spinner": "Processing PDF...",
        "results_header": "Results:",
        "terms_found_header": "Search terms found in the document:",
        "relevant_snippets_header": "Relevant Snippets:",
        "no_snippets_found": "No snippets found for the specified terms.",
        "no_terms_found": "None of the search terms were found in the document.",
        "please_enter_terms": "Please enter search terms in the text box.",
        "please_upload_file": "Please upload one or more PDF files.",
        "error_reading_pdf": "Error reading PDF:",
        "pdf_corruption_warning": "Please check if the PDF file is not corrupted, password-protected, or in an invalid format.",
        "select_language": "Select Language:",
        "no_keywords_info": "No keywords found (excluding stopwords and short words).",
        "search_options_header": "Search Options:",
        "case_sensitive_checkbox": "Case-sensitive search",
        "whole_word_checkbox": "Whole words only",
        "stats_header": "Document Statistics:",
        "total_words_count": "Total words in document:",
        "term_occurrences": "Term Occurrences:",
        "download_results_button": "Download Results (.txt)",
        "download_filename": "search_results.txt",
        "page_number_label": "Page:",
        "clear_button_label": "Clear All",
        "pdf_manual_conversion_guidance": "If this error persists, the PDF might have advanced protection. Try converting the PDF to plain text (TXT) using an online tool (e.g., Smallpdf 'PDF to TXT' or Adobe Acrobat online) and then upload the TXT to the text input field for searching, or use a PDF without such protection.",
        "process_button_label": "Process Search",
        "initial_guidance": "Upload one or more PDF files and enter search terms. Then click 'Process Search'.",
        "copy_results_button": "Copy Results",
        "copy_instructions": "Copy the text below:",
        "results_from_file": "Results from file:",
        "processing_file": "Processing file:",
        "filter_snippets_label": "Filter snippets by term:",
        "sort_snippets_label": "Sort snippets by:",
        "sort_option_page": "Page (ascending)",
        "sort_option_file_page": "File and Page (ascending)",
        "all_terms_filter": "All Terms",
        "enable_regex_checkbox": "Enable Regex Search",
        "about_header": "About / Help",
        "about_content_1": "This web application allows you to extract text from PDFs and search for specific terms or phrases. You can upload multiple PDFs and customize your search.",
        "about_content_2": "Results include document statistics and relevant snippets with page numbers and source files. You can download or copy the results.",
        "about_limitations": "**Known Limitations:**\n- **Protected/Encrypted PDFs:** Some PDFs with advanced protection cannot be read directly. A suggestion appears if there's a reading error.\n- **Performance:** Very large PDFs may take time to process and consume more memory.",
        "process_button_icon": "🚀",
        "clear_button_icon": "🗑️",
        "download_button_icon": "📥",
        "copy_button_icon": "📋",
        "regex_help_text": "Use Regular Expression syntax. E.g., 'email:(\\S+@\\S+)' for emails.",
        "expander_results_header": "View Results",
        "expander_results_header_with_count": "View Results ({count} snippets found)",
        "favicon_icon": "📚"
    }
}

SUPPORTED_LANGUAGES = {
    "pt": "Português",
    "en": "English"
}
